// mainnet
export const ETHEREUM_MAINNET_CHAIN_ID = 1;
export const ARBITRUM_MAINNET_CHAIN_ID = 42_161;
export const POLYGON_MAINNET_CHAIN_ID = 137;
export const OPTIMISM_MAINNET_CHAIN_ID = 10;
export const AVALANCHE_MAINNET_CHAIN_ID = 43_114;
export const BNB_MAINNET_CHAIN_ID = 204;
export const BASE_MAINNET_CHAIN_ID = 8453;
export const BITCOIN_CHAIN_ID = 0;

// testnet
export const SEPOLIA_CHAIN_ID = 11155111;
export const SEPOLIA_ARBITRUM_CHAIN_ID = 421614;
export const POLYGON_AMOY_TESTNET_ID = 80002;
export const OPTIMISM_SEPOLIA_TESTNET_ID = 11155420;
export const AVALANCHE_FUJI_TESTNET_ID = 43113;
export const BNB_SMART_CHAIN_TESTNET_ID = 97;
export const BASE_SEPOLIA_TESTNET_ID = 84532;

export const SOLANA_CHAIN_ID = 42;

// todo: mainnet list
export const SUPPORTED_ETH_CHAINS = [
  SEPOLIA_CHAIN_ID,
  SEPOLIA_ARBITRUM_CHAIN_ID,
  POLYGON_AMOY_TESTNET_ID,
  OPTIMISM_SEPOLIA_TESTNET_ID,
  AVALANCHE_FUJI_TESTNET_ID,
  BNB_SMART_CHAIN_TESTNET_ID,
  BASE_SEPOLIA_TESTNET_ID,
];
export const SUPPORTED_SOL_CHAINS = [SOLANA_CHAIN_ID];
