/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Raffle {
  export type LastRoundStruct = {
    poolBalance: BigNumberish;
    endTime: BigNumberish;
    roundId: BigNumberish;
    token: AddressLike;
    status: BigNumberish;
  };

  export type LastRoundStructOutput = [
    poolBalance: bigint,
    endTime: bigint,
    roundId: bigint,
    token: string,
    status: bigint
  ] & {
    poolBalance: bigint;
    endTime: bigint;
    roundId: bigint;
    token: string;
    status: bigint;
  };

  export type TicketStruct = {
    price: BigNumberish;
    owner: AddressLike;
    timestamp: BigNumberish;
    isBonus: boolean;
  };

  export type TicketStructOutput = [
    price: bigint,
    owner: string,
    timestamp: bigint,
    isBonus: boolean
  ] & { price: bigint; owner: string; timestamp: bigint; isBonus: boolean };

  export type RoundStruct = {
    status: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    poolBalance: BigNumberish;
    commissionBalance: BigNumberish;
    tickets: Raffle.TicketStruct[];
    winnerAddress: AddressLike;
    winnerTicket: BigNumberish;
  };

  export type RoundStructOutput = [
    status: bigint,
    startTime: bigint,
    endTime: bigint,
    poolBalance: bigint,
    commissionBalance: bigint,
    tickets: Raffle.TicketStructOutput[],
    winnerAddress: string,
    winnerTicket: bigint
  ] & {
    status: bigint;
    startTime: bigint;
    endTime: bigint;
    poolBalance: bigint;
    commissionBalance: bigint;
    tickets: Raffle.TicketStructOutput[];
    winnerAddress: string;
    winnerTicket: bigint;
  };

  export type RoundPlayerDataWithAddressStruct = {
    player: AddressLike;
    ticketsCount: BigNumberish;
    hasBonusTicket: boolean;
  };

  export type RoundPlayerDataWithAddressStructOutput = [
    player: string,
    ticketsCount: bigint,
    hasBonusTicket: boolean
  ] & { player: string; ticketsCount: bigint; hasBonusTicket: boolean };
}

export interface RaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "acceptOwnership"
      | "activeRounds"
      | "buyTicket"
      | "checkUpkeep"
      | "getCurrentRaffleRoundId"
      | "getLastRounds"
      | "getRaffleRoundCount"
      | "getRaffleRoundData"
      | "getRoleAdmin"
      | "getRoundResult"
      | "getSupportedTokens"
      | "getTicketPriceForToken"
      | "getTicketPriceInBtc"
      | "getTicketPriceInNative"
      | "getTicketPriceInUsd"
      | "grantRole"
      | "hasRole"
      | "isSupportedToken"
      | "isSupportedTokenMapping"
      | "owner"
      | "performUpkeep"
      | "rawFulfillRandomWords"
      | "renounceRole"
      | "resetCustomPrice"
      | "revokeRole"
      | "s_vrfCoordinator"
      | "setCoordinator"
      | "setCustomPrice"
      | "supportedTokenCount"
      | "supportedTokens"
      | "supportsInterface"
      | "transferOwnership"
      | "vrfRequestToRoundContext"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoordinatorSet"
      | "FirstTicketBonusAwarded"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StatusChanged"
      | "TicketPurchased"
      | "WinnerPicked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeRounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRaffleRoundId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastRounds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleRoundCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleRoundData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundResult",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketPriceForToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketPriceInBtc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketPriceInNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketPriceInUsd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedTokenMapping",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetCustomPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_vrfCoordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCoordinator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCustomPrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vrfRequestToRoundContext",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRaffleRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleRoundCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketPriceForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketPriceInBtc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketPriceInNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketPriceInUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedTokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetCustomPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_vrfCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCustomPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vrfRequestToRoundContext",
    data: BytesLike
  ): Result;
}

export namespace CoordinatorSetEvent {
  export type InputTuple = [vrfCoordinator: AddressLike];
  export type OutputTuple = [vrfCoordinator: string];
  export interface OutputObject {
    vrfCoordinator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirstTicketBonusAwardedEvent {
  export type InputTuple = [
    token: AddressLike,
    roundId: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish,
    roundStartTime: BigNumberish,
    roundEndTime: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    roundId: bigint,
    buyer: string,
    timestamp: bigint,
    roundStartTime: bigint,
    roundEndTime: bigint
  ];
  export interface OutputObject {
    token: string;
    roundId: bigint;
    buyer: string;
    timestamp: bigint;
    roundStartTime: bigint;
    roundEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedEvent {
  export type InputTuple = [
    token: AddressLike,
    roundId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    caller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    roundId: bigint,
    oldStatus: bigint,
    newStatus: bigint,
    caller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    token: string;
    roundId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
    caller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [
    token: AddressLike,
    roundId: BigNumberish,
    buyer: AddressLike,
    count: BigNumberish,
    totalAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    roundId: bigint,
    buyer: string,
    count: bigint,
    totalAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    token: string;
    roundId: bigint;
    buyer: string;
    count: bigint;
    totalAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerPickedEvent {
  export type InputTuple = [
    token: AddressLike,
    roundId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [token: string, roundId: bigint, timestamp: bigint];
  export interface OutputObject {
    token: string;
    roundId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Raffle extends BaseContract {
  connect(runner?: ContractRunner | null): Raffle;
  waitForDeployment(): Promise<this>;

  interface: RaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  activeRounds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        token: string;
        roundId: bigint;
        vrfRequestTime: bigint;
      }
    ],
    "view"
  >;

  buyTicket: TypedContractMethod<
    [token: AddressLike, count: BigNumberish, maxCost: BigNumberish],
    [void],
    "payable"
  >;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;

  getCurrentRaffleRoundId: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getLastRounds: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [Raffle.LastRoundStructOutput[]],
    "view"
  >;

  getRaffleRoundCount: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getRaffleRoundData: TypedContractMethod<
    [token: AddressLike, roundId: BigNumberish],
    [
      [
        Raffle.RoundStructOutput,
        Raffle.RoundPlayerDataWithAddressStructOutput[]
      ] & {
        round: Raffle.RoundStructOutput;
        players: Raffle.RoundPlayerDataWithAddressStructOutput[];
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoundResult: TypedContractMethod<
    [token: AddressLike, roundId: BigNumberish],
    [
      [string, bigint, string[], bigint] & {
        winnerAddress: string;
        winnerTicket: bigint;
        roundPlayers: string[];
        prizeAmount: bigint;
      }
    ],
    "view"
  >;

  getSupportedTokens: TypedContractMethod<[], [string[]], "view">;

  getTicketPriceForToken: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getTicketPriceInBtc: TypedContractMethod<[], [bigint], "view">;

  getTicketPriceInNative: TypedContractMethod<[], [bigint], "view">;

  getTicketPriceInUsd: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  isSupportedTokenMapping: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  performUpkeep: TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resetCustomPrice: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  s_vrfCoordinator: TypedContractMethod<[], [string], "view">;

  setCoordinator: TypedContractMethod<
    [_vrfCoordinator: AddressLike],
    [void],
    "nonpayable"
  >;

  setCustomPrice: TypedContractMethod<
    [token: AddressLike, customPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedTokenCount: TypedContractMethod<[], [bigint], "view">;

  supportedTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  vrfRequestToRoundContext: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { token: string; roundId: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeRounds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        token: string;
        roundId: bigint;
        vrfRequestTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buyTicket"
  ): TypedContractMethod<
    [token: AddressLike, count: BigNumberish, maxCost: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentRaffleRoundId"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastRounds"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [Raffle.LastRoundStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRaffleRoundCount"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRaffleRoundData"
  ): TypedContractMethod<
    [token: AddressLike, roundId: BigNumberish],
    [
      [
        Raffle.RoundStructOutput,
        Raffle.RoundPlayerDataWithAddressStructOutput[]
      ] & {
        round: Raffle.RoundStructOutput;
        players: Raffle.RoundPlayerDataWithAddressStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoundResult"
  ): TypedContractMethod<
    [token: AddressLike, roundId: BigNumberish],
    [
      [string, bigint, string[], bigint] & {
        winnerAddress: string;
        winnerTicket: bigint;
        roundPlayers: string[];
        prizeAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTicketPriceForToken"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTicketPriceInBtc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTicketPriceInNative"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTicketPriceInUsd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSupportedTokenMapping"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resetCustomPrice"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "s_vrfCoordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCoordinator"
  ): TypedContractMethod<[_vrfCoordinator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCustomPrice"
  ): TypedContractMethod<
    [token: AddressLike, customPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedTokenCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vrfRequestToRoundContext"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { token: string; roundId: bigint }],
    "view"
  >;

  getEvent(
    key: "CoordinatorSet"
  ): TypedContractEvent<
    CoordinatorSetEvent.InputTuple,
    CoordinatorSetEvent.OutputTuple,
    CoordinatorSetEvent.OutputObject
  >;
  getEvent(
    key: "FirstTicketBonusAwarded"
  ): TypedContractEvent<
    FirstTicketBonusAwardedEvent.InputTuple,
    FirstTicketBonusAwardedEvent.OutputTuple,
    FirstTicketBonusAwardedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StatusChanged"
  ): TypedContractEvent<
    StatusChangedEvent.InputTuple,
    StatusChangedEvent.OutputTuple,
    StatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPurchased"
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerPicked"
  ): TypedContractEvent<
    WinnerPickedEvent.InputTuple,
    WinnerPickedEvent.OutputTuple,
    WinnerPickedEvent.OutputObject
  >;

  filters: {
    "CoordinatorSet(address)": TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;
    CoordinatorSet: TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;

    "FirstTicketBonusAwarded(address,uint32,address,uint256,uint256,uint256)": TypedContractEvent<
      FirstTicketBonusAwardedEvent.InputTuple,
      FirstTicketBonusAwardedEvent.OutputTuple,
      FirstTicketBonusAwardedEvent.OutputObject
    >;
    FirstTicketBonusAwarded: TypedContractEvent<
      FirstTicketBonusAwardedEvent.InputTuple,
      FirstTicketBonusAwardedEvent.OutputTuple,
      FirstTicketBonusAwardedEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StatusChanged(address,uint32,uint8,uint8,address,uint256)": TypedContractEvent<
      StatusChangedEvent.InputTuple,
      StatusChangedEvent.OutputTuple,
      StatusChangedEvent.OutputObject
    >;
    StatusChanged: TypedContractEvent<
      StatusChangedEvent.InputTuple,
      StatusChangedEvent.OutputTuple,
      StatusChangedEvent.OutputObject
    >;

    "TicketPurchased(address,uint32,address,uint40,uint256,uint256)": TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;

    "WinnerPicked(address,uint32,uint256)": TypedContractEvent<
      WinnerPickedEvent.InputTuple,
      WinnerPickedEvent.OutputTuple,
      WinnerPickedEvent.OutputObject
    >;
    WinnerPicked: TypedContractEvent<
      WinnerPickedEvent.InputTuple,
      WinnerPickedEvent.OutputTuple,
      WinnerPickedEvent.OutputObject
    >;
  };
}
