root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - '@typescript-eslint/recommended'
  - prettier
rules:
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-non-null-assertion': warn
  prettier/prettier: error
  no-console: warn
  no-debugger: error
env:
  node: true
  es6: true
  mocha: true
