// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { ThemeConfig, Typography } from "antd";

export const antdTheme: ThemeConfig = {
  hashed: false,
  token: {
    fontFamily: '"Geist Variable", sans-serif',
    fontSize: 16,
    colorPrimary: "#3F3F46",
    colorInfo: "#0d5bdb",
    colorLink: "#4242fd",
    colorError: "#DC2626",
    colorWarning: "#EAB308",
    colorSuccess: "#4bb34b",
    colorTextBase: "var(--color-neutral-text-neutral-foreground, #FFF)",
  },
  components: {
    Statistic: {
      fontFamily: '"Geist Mono Variable", sans-serif',
    },
    Switch: {
      trackHeight: 24,
      trackMinWidth: 44,
      handleSize: 20,
      handleSizeLoading: 20,
    },
    Select: {
      zIndexPopup: "",
      optionSelectedColor: "",
      optionSelectedFontWeight: "",
      optionSelectedBg: "",
      optionActiveBg: "",
      optionPadding: "",
      optionFontSize: "",
      optionLineHeight: "",
      optionHeight: "",
      selectorBg: "",
      clearBg: "",
      singleItemHeightLG: "",
      showArrowPaddingInlineEnd: "",
      hoverBorderColor: "",
      activeBorderColor: "",
      activeOutlineColor: "",
    },
    Typography: {
      colorError: "",
      colorErrorActive: "",
      colorErrorHover: "",
      colorLink: "",
      colorLinkActive: "",
      colorLinkHover: "",
      colorSuccess: "",
      colorText: "",
      colorTextDescription: "",
      colorTextDisabled: "",
      colorTextHeading: "",
      colorWarning: "",
      fontFamilyCode: "",
      fontSize: "",
      fontSizeHeading1: "",
      fontSizeHeading2: "",
      fontSizeHeading3: "",
      fontSizeHeading4: "",
      fontSizeHeading5: "",
      fontWeightStrong: "",
      lineHeight: "",
      lineHeightHeading1: "",
      lineHeightHeading2: "",
      lineHeightHeading3: "",
      lineHeightHeading4: "",
      lineHeightHeading5: "",
      linkDecoration: "",
      linkHoverDecoration: "",
      marginXS: "",
      marginXXS: "",
      // motionDurationSlow: '',
      paddingSM: "",
      titleMarginBottom: "",
      titleMarginTop: "",
    },
    Button: {
      borderColorDisabled: "",
      borderRadius: "",
      borderRadiusLG: "",
      borderRadiusSM: "",
      colorBgContainer: "",
      colorBgContainerDisabled: "",
      colorBgTextActive: "",
      colorBorder: "",
      colorError: "",
      colorErrorActive: "",
      colorErrorBg: "",
      colorErrorBgActive: "",
      colorErrorBorderHover: "",
      colorErrorHover: "",
      colorLink: "",
      colorLinkActive: "",
      colorLinkHover: "",
      colorPrimary: "",
      colorPrimaryActive: "",
      colorPrimaryBorder: "",
      colorPrimaryHover: "",
      colorText: "",
      colorTextDisabled: "",
      colorTextLightSolid: "",
      contentFontSize: "",
      contentFontSizeLG: "",
      contentFontSizeSM: "",
      contentLineHeight: "",
      contentLineHeightLG: "",
      contentLineHeightSM: "",
      controlHeight: "",
      controlHeightLG: "",
      controlHeightSM: "",
      dangerColor: "",
      dangerShadow: "",
      defaultActiveBg: "",
      defaultActiveBorderColor: "",
      defaultActiveColor: "",
      defaultBg: "",
      defaultBorderColor: "",
      defaultColor: "",
      defaultGhostBorderColor: "",
      defaultGhostColor: "",
      defaultHoverBg: "",
      defaultHoverBorderColor: "",
      defaultHoverColor: "",
      defaultShadow: "",
      fontSize: "",
      fontWeight: "",
      ghostBg: "",
      groupBorderColor: "",
      lineType: "",
      lineWidth: "",
      lineWidthFocus: "",
      linkHoverBg: "",
      marginXS: "",
      // motionDurationMid: '',
      // motionDurationSlow: '',
      // motionEaseInOut: '',
      onlyIconSize: "",
      onlyIconSizeLG: "",
      onlyIconSizeSM: "",
      opacityLoading: "",
      paddingBlock: "",
      paddingBlockLG: "",
      paddingBlockSM: "",
      paddingInline: "",
      paddingInlineLG: "",
      paddingInlineSM: "",
      paddingXS: "",
      primaryColor: "",
      primaryShadow: "",
      textHoverBg: "",
    },
    Checkbox: {
      // borderRadiusSM:'',
      // colorBgContainer:'',
      // colorBgContainerDisabled: '',
      // colorBorder:'',
      // colorPrimary:'',
      // colorPrimaryBorder:'',
      // colorPrimaryHover:'',
      // colorText:'',
      // colorTextDisabled:'',
      // colorWhite:'',
      // controlInteractiveSize:'',
      // fontFamily:'',
      // fontSize:'',
      // fontSizeLG:'',
      // lineHeight:'',
      // lineType:'',
      // lineWidth:'',
      // lineWidthBold:'',
      // lineWidthFocus:'',
      // marginXS:'',
      // motionDurationFast:'',
      // motionDurationMid:'',
      // motionDurationSlow:'',
      // motionEaseInBack:'',
      // motionEaseOutBack:'',
      // paddingXS:'',

      borderRadiusSM: 4,
      lineWidth: 1,
      paddingXS: 12,
      colorBorder: "rgba(24, 24, 27, 0.1)", // '#aaabad' ???, // --Gray-gray-6
      colorBgContainerDisabled: "#fff", // --Gray-white
      controlInteractiveSize: 20,
    },
    Switch: {
      handleSize: 16,
      trackHeight: 22,
      trackMinWidth: 42,
      trackPadding: 2,
      handleShadow: "none",
    },
    Notification: {
      width: "100%",
      maxWidth: 400,
      borderRadiusLG: 12,
      borderRadiusSM: 12,
      boxShadow: "0px 4px 4px 0px rgba(0, 32, 51, 0.04), 0px 8px 24px 0px rgba(0, 32, 51, 0.12);",
      paddingContentHorizontalLG: 16,
      paddingLG: 16,
      paddingMD: 16,
      margin: 0,
      // marginLG: 44,
      marginSM: "",
      marginXS: "",
    },
    Modal: {
      borderRadiusLG: 16,
      borderRadiusSM: 16,
      boxShadow:
        "0px 426px 119px 0px rgba(24, 24, 27, 0.00), 0px 273px 109px 0px rgba(24, 24, 27, 0.01), 0px 154px 92px 0px rgba(24, 24, 27, 0.05), 0px 68px 68px 0px rgba(24, 24, 27, 0.09), 0px 17px 38px 0px rgba(24, 24, 27, 0.10);",
    },
  },
};

Typography.defaultProps = {
  component: "p",
};
